openapi: 3.1.0
info:
  title: Google Sheets Forwarder
  description: API להעברת נתונים לטבלת Google Sheets עם Insert, Update, Delete.
  version: '1.0.0'

servers:
  - url: https://gpt-sheets-server.onrender.com

paths:
  /insert:
    post:
      summary: הוספת שורה חדשה לטבלת Google Sheets
      operationId: insertRow
      security:
        - api_key: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - row_data
              properties:
                row_data:
                  type: object
                  properties:
                    "1": { type: string, example: "רות לוי" }
                    "2": { type: string, example: "050-1111111" }
                    "3": { type: string, example: "test@example.com" }
                    "4": { type: string, example: "בקשה להצעת מחיר" }
                    "5": { type: string, example: "יצירת קשר טלפוני" }
                    "6": { type: string, example: "ממתין" }
                    "9": { type: string, example: "2025-04-16" }
      responses:
        '200':
          description: הצלחה

  /update:
    post:
      summary: עדכון שורה קיימת לפי פילטר (עמודה 1)
      operationId: updateRow
      security:
        - api_key: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - filter
                - row_data
              properties:
                filter:
                  type: object
                  properties:
                    "1": { type: string, example: "רות לוי" }
                row_data:
                  type: object
                  properties:
                    "5": { type: string, example: "עבר לטיפול" }
                    "6": { type: string, example: "לתאם שיחה" }
      responses:
        '200':
          description: הצלחה

  /delete:
    post:
      summary: מחיקת שורה לפי פילטר (עמודה 1)
      operationId: deleteRow
      security:
        - api_key: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - filter
              properties:
                filter:
                  type: object
                  properties:
                    "1": { type: string, example: "רות לוי" }
      responses:
        '200':
          description: הצלחה

components:
  securitySchemes:
    api_key:
      type: apiKey
      in: header
      name: x-api-key
