openapi: 3.1.0
info:
  title: Google Sheets Forwarder
  description: API להעברת נתונים לטבלת Google Sheets עם Insert, Update, Delete.
  version: '1.0.0'
servers:
  - url: https://gpt-sheets-server.onrender.com
paths:
  /insert:
    post:
      summary: הוספת שורה חדשה
      operationId: insertRow
      security:
        - api_key: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - row_data
              properties:
                row_data:
                  type: object
                  additionalProperties:
                    type: string
      responses:
        '200':
          description: success
  /update:
    post:
      summary: עדכון שורה
      operationId: updateRow
      security:
        - api_key: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - filter
                - row_data
              properties:
                filter:
                  type: object
                  additionalProperties:
                    type: string
                row_data:
                  type: object
                  additionalProperties:
                    type: string
      responses:
        '200':
          description: success
  /delete:
    post:
      summary: מחיקת שורה
      operationId: deleteRow
      security:
        - api_key: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - filter
              properties:
                filter:
                  type: object
                  additionalProperties:
                    type: string
      responses:
        '200':
          description: success
components:
  securitySchemes:
    api_key:
      type: apiKey
      in: header
      name: x-api-key
