openapi: 3.1.0
info:
  title: Google Sheets Forwarder
  description: API להעברת נתונים לטבלת Google Sheets עם Insert, Update, Delete.
  version: '1.0.0'

servers:
  - url: https://gpt-sheets-server.onrender.com

paths:
  /insert:
    post:
      summary: הוספת שורה חדשה לטבלה
      operationId: insertRow
      security:
        - api_key: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                row_data:
                  type: object
              required:
                - row_data
      responses:
        '200':
          description: הצלחה

  /update:
    post:
      summary: עדכון שורה לפי פילטר (עמודה 1)
      operationId: updateRow
      security:
        - api_key: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                filter:
                  type: object
                row_data:
                  type: object
              required:
                - filter
                - row_data
      responses:
        '200':
          description: הצלחה

  /delete:
    post:
      summary: מחיקת שורה לפי פילטר (עמודה 1)
      operationId: deleteRow
      security:
        - api_key: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                filter:
                  type: object
              required:
                - filter
      responses:
        '200':
          description: הצלחה

  /forward:
    post:
      summary: שליחה גנרית לפי action (insert_row / update_row / delete_row)
      operationId: forwardWebhook
      security:
        - api_key: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                action:
                  type: string
                  example: insert_row
                table:
                  type: string
                  example: DB MASTER
                row_data:
                  type: object
                  example:
                    "1": "רות לוי"
                    "2": "050-1234567"
                    "3": "שיחה"
                    "4": "רוצה הצעת מחיר"
                    "5": "חם"
                    "6": "לחזור אליה בהקדם"
                    "9": "2025-04-16"
                filter:
                  type: object
                  example:
                    "1": "רות לוי"
              required:
                - action
                - table
      responses:
        '200':
          description: הצלחה

components:
  securitySchemes:
    api_key:
      type: apiKey
      in: header
      name: x-api-key
  schemas: {}
