openapi: 3.1.0
info:
  title: Google Sheets Forwarder
  description: API להעברת נתונים לטבלת Google Sheets עם Insert, Update, Delete.
  version: '1.0.0'
servers:
  - url: https://gpt-sheets-server.onrender.com
paths:
  /insert:
    post:
      summary: הוספת שורה חדשה לטבלת Google Sheets
      operationId: insertRow
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - row_data
              properties:
                row_data:
                  type: object
                  additionalProperties:
                    type: string
      responses:
        '200':
          description: הצלחה
  /update:
    post:
      summary: עדכון שורה קיימת לפי פילטר (עמודה 1)
      operationId: updateRow
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - filter
                - row_data
              properties:
                filter:
                  type: object
                  additionalProperties:
                    type: string
                row_data:
                  type: object
                  additionalProperties:
                    type: string
      responses:
        '200':
          description: הצלחה
  /delete:
    post:
      summary: מחיקת שורה לפי פילטר (עמודה 1)
      operationId: deleteRow
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - filter
              properties:
                filter:
                  type: object
                  additionalProperties:
                    type: string
      responses:
        '200':
          description: הצלחה
