openapi: 3.1.0
info:
  title: Google Sheets Forwarder
  description: API להעברת נתונים לטבלת Google Sheets עם Insert, Update, Delete.
  version: '1.0.0'
servers:
  - url: https://gpt-sheets-server.onrender.com
paths:
  /insert:
    post:
      summary: הוספת שורה חדשה
      operationId: insertRow
      security:
        - ApiKeyAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [row_data]
              properties:
                row_data:
                  type: object
                  additionalProperties: true
      responses:
        '200':
          description: הצלחה
  /update:
    post:
      summary: עדכון שורה
      operationId: updateRow
      security:
        - ApiKeyAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [filter, row_data]
              properties:
                filter:
                  type: object
                  additionalProperties: true
                row_data:
                  type: object
                  additionalProperties: true
      responses:
        '200':
          description: הצלחה
  /delete:
    post:
      summary: מחיקת שורה
      operationId: deleteRow
      security:
        - ApiKeyAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [filter]
              properties:
                filter:
                  type: object
                  additionalProperties: true
      responses:
        '200':
          description: הצלחה

components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: X-API-Key
